### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-3-sintesis-Heidi-19#2]
[Sintesis - Webinar gratuito.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Heidi-19/files/12504877/Sintesis.-.Webinar.gratuito.pdf)

**Comment by bg55-a** [comment]
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
